script: true

stages:
  - name: Jorts
    if: type = cron OR commit_message =~ /jortleby/ OR (tag IS present AND tag =~ /^hello$/)
  - Jants
  - okay

jobs:
  include:
    - stage: Jorts
      script: /bin/true
    - stage: Jants
      script: /bin/true
    - stage: okay
      script: /bin/true
