script: true
notifications:
  email: false

stages:
  - Jorts :two_men_holding_hands:
  - Jants
  - okay

jobs:
  include:
    - stage: "Jorts :two_men_holding_hands:"
      env: FF=true
      script: /bin/true
    - stage: "Jorts :two_men_holding_hands:"
      env: GG=true
      script: /bin/false
    - stage: "Jorts :two_men_holding_hands:"
      env: HH=true
      script: /bin/false
    - stage: Jants
      script: /bin/true
    - stage: Jants
      env: FF=true
      script: /bin/false
    - stage: Jants
      env: GG=true
      script: /bin/false
    - stage: Jants
      env: HH=true
      script: /bin/false
    - stage: Jants
      env: II=true
      script: /bin/false
    - stage: Jants
      env: JJ=true
      script: /bin/false
    - stage: Jants
      env: KK=true
      script: /bin/false
    - stage: okay
      script: /bin/true
    - stage: okay
      script: /bin/true

  allow_failures:
    - stage: "Jorts :two_men_holding_hands:"
      env: GG=true
      script: /bin/false
    - stage: "Jorts :two_men_holding_hands:"
      env: HH=true
      script: /bin/false
    - stage: Jants
      env: FF=true
      script: /bin/false
    - stage: Jants
      env: GG=true
      script: /bin/false
    - stage: Jants
      env: HH=true
      script: /bin/false
    - stage: Jants
      env: II=true
      script: /bin/false
    - stage: Jants
      env: JJ=true
      script: /bin/false
    - stage: Jants
      env: KK=true
      script: /bin/false
