language: ruby
rvm:
  - "2.3.0"
sudo: false
before_install:
  - rvm get stable --auto-dotfiles
  - gem install bundler
  - nvm list
  - echo "🙃"
script:
  - rvm -v
  - rvm alias list
  - ruby -v
  - rvm list
  - ruby test.rb
notifications:
  email: false
