language: ruby
rvm:
  - "2.3.0"
  - "2.3"
  - "2.3.1"
  - "2.2"
  - "2.1.9"
  - "jruby-head"
sudo: false
before_install:
  - rvm get stable --auto-dotfiles
  - gem install bundler
script:
  - rvm -v
  - rvm alias list
  - ruby -v
  - rvm list
  - ruby test.rb
notifications:
  email: false
