script: true
notifications:
  email: false

stages:
  - Jorts :two_men_holding_hands:
  - Jants
  - okay

jobs:
  include:
    - stage: "Jorts :two_men_holding_hands:"
      script: /bin/true
    - stage: "Jorts :two_men_holding_hands:"
      script: /bin/true
    - stage: Jants
      script: /bin/true
    - stage: Jants
      script: /bin/false
    - stage: okay
      script: /bin/true
    - stage: okay
      script: /bin/true
