script: true

stages:
  - name: Jorts :two_men_holding_hands:
    if: type = cron OR commit_message =~ /\[jortleby\]/ or (tag IS present AND tag =~ /^hello[\d]+/)
  - Jants
  - okay

jobs:
  include:
    - stage: "Jorts :two_men_holding_hands:"
      script: /bin/true
    - stage: Jants
      script: /bin/true
    - stage: okay
      script: /bin/true
