language: python
sudo: required
dist: trusty
install:
  - sudo apt-get update
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libav-tools libavcodec-extra-56
script:
  - echo 'jorts'
notifications:
  email: false
