script: true

stages:
  - name: Jorts
    if: type = cron OR (commit_message =~ /jortleby/) OR (tag IS present AND tag =~ /^hello/)
  - Jants
  - okay

jobs:
  include:
    - stage: Jorts
      script: /bin/true
    - stage: Jants
      script: /bin/true
    - stage: okay
      script: /bin/true

notifications:
  slack:
    secure: R9j7/hxidVqLUkvfkRO1VdE/jxzdHgoqr2wy1W+GkAj8I93S0gH8bX4kzxa+HDuCKtjeaM/BdPtcGi8NtprkGJrcfls/CPfvuRM6sTd1iBBTmygmJ2X1Nd8FiU3XGDDxUbXkS4VAf5pwIXVv4rYEL4IqjnlXwH2p1CHdlKzA4kxStEf3bpUZtCs9rRxwcnOSJVwJjAfgC0anTdyvEcv0ZncWLOvpzlVKdnj2aaQKdk3ZQyazWC6NY/rMfXKtsYtkkcmdHD3PznAcIyzEaVBrAYaDK2ol58pAJo+0ihVTNJY/yZNk/XsrqFdnyrvlisXo0FBmiV7LXizPdOEhf0/H9JnVEfkntCOcLXt3CAkj3kNJtyhpm67qro+rzrCNLIRLIilE/wOMPnNJ3QNVbE27h2rLhfnFl+C/HtKXl9rAVvQ0XGfM+yxrzmchaOpXpHWyhXbFt8SqxxpZGGCJiwTl2phMuJdg9xy6FXaL/V8e43/Est5Gg2WNT3CtCz5RXT+oOShNzsdyi4RDs0kQu8Ut2EsuQQRkTUc6iL/1l2mLgqU7DeKnJZ1PmCWXJQBd5q7tM+rv93nVoq9uZqTTCR6fAbxP4/kYRnAX01DtlCGYiG0DEBaILoQcl/QKn+2TRhTefRyx8GOSNvv5c/cIlkefboI7N7FZtWFkyYeqhF6RE54=
    on_success: change
    on_failure: change
    on_error: change
