language: ruby
rvm:
  - "2.3.0"
  - "2.3"
  - "2.3.1"
  - "2.2"
before_install:
  - rvm get stable --auto-dotfiles
script:
  - rvm -v
  - rvm alias list
  - ruby -v
  - rvm list
notifications:
  email: false
